spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO}  # 개발: update, 운영: validate
    show-sql: true  # 개발용으로만 true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:test@test.test}
    password: ${MAIL_PASSWORD:testpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-validity: 1800000  # 30분
      refresh-token-validity: 1209600000  # 14일

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    team2.stk: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
